name: remed
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  google_sign_in: ^6.3.0
  cloud_firestore: ^5.6.6
  shared_preferences: ^2.2.3

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/login_pic.png
    - assets/user.png
    - assets/google_icon.png
    - assets/ob_bg1.png
    - assets/ob_bg2.png
    - assets/ob_bg3.png

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
