// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAELFWXH__yuAOS9V78MksSsGnaj5jYKh8',
    appId: '1:584481431715:web:fab7d82594a60b60135f16',
    messagingSenderId: '584481431715',
    projectId: 'remed-235a3',
    authDomain: 'remed-235a3.firebaseapp.com',
    storageBucket: 'remed-235a3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiLJAKT9sK8wRbbDJ2u4w7zmzTy2JYflk',
    appId: '1:584481431715:android:5a3b711172bcb836135f16',
    messagingSenderId: '584481431715',
    projectId: 'remed-235a3',
    storageBucket: 'remed-235a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuxmiIaMMjeWOakAkmJa2eE1A9wsAC2rA',
    appId: '1:584481431715:ios:158b6edba9234960135f16',
    messagingSenderId: '584481431715',
    projectId: 'remed-235a3',
    storageBucket: 'remed-235a3.firebasestorage.app',
    iosClientId: '584481431715-0fbbs37q29k2ou2br48qdm2bqku2jsfp.apps.googleusercontent.com',
    iosBundleId: 'com.example.remed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuxmiIaMMjeWOakAkmJa2eE1A9wsAC2rA',
    appId: '1:584481431715:ios:158b6edba9234960135f16',
    messagingSenderId: '584481431715',
    projectId: 'remed-235a3',
    storageBucket: 'remed-235a3.firebasestorage.app',
    iosClientId: '584481431715-0fbbs37q29k2ou2br48qdm2bqku2jsfp.apps.googleusercontent.com',
    iosBundleId: 'com.example.remed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAELFWXH__yuAOS9V78MksSsGnaj5jYKh8',
    appId: '1:584481431715:web:d1bb9578d728c0ce135f16',
    messagingSenderId: '584481431715',
    projectId: 'remed-235a3',
    authDomain: 'remed-235a3.firebaseapp.com',
    storageBucket: 'remed-235a3.firebasestorage.app',
  );
}
